- id: '1717151243750'
  alias: Update Goodwe Solar Inverter
  description: ''
  trigger:
  - platform: time_pattern
    seconds: /12
  condition:
  - condition: sun
    before: sunset
    before_offset: 01:00:00
    after: sunrise
    after_offset: -01:00:00
  action:
  - service: homeassistant.update_entity
    data: {}
    target:
      entity_id: sensor.total_pv_generation
  mode: single
