# Loads default set of integrations. Do not remove.
default_config:

automation manual: !include_dir_merge_list automations
automation ui: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

rest_command: !include_dir_merge_named rest_commands

template: !include_dir_merge_list templates

python_script:

lovelace: !include dashboards.yaml
